language: objective-c
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script: xctool -project NJKWebViewProgress.xcodeproj -scheme NJKWebViewProgressTests -sdk iphonesimulator run-tests
